# -*- coding: utf-8 -*-
"""geometric_canaries_streaming_rollback_v0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBcF0p9xcDMIIoBWjI2_pDGF9zB4EKlH

# Geometric Canaries — streaming CoT checkpoint / rollback

**Question.** If we segment a proof attempt into reasoning steps, can we (a) catch faulty
logic at the step where it appears and (b) make proving *cheaper* by rolling back to the
last safe checkpoint instead of resampling from scratch?

**Model.** `deepseek-ai/DeepSeek-Prover-V2-7B`, 4-bit, single Colab GPU.
Set `DRY_RUN = True` to smoke-test the pipeline with a tiny model first.

**What changed vs. the previous notebook**

| before | now | why |
|---|---|---|
| generate 512 tokens → segment → detect → roll back | detect **online** at each segment boundary during generation | tokens after the first bad segment are never generated |
| rollback re-encodes the whole prefix every round | checkpoint = **KV-cache length**; rollback = `cache.crop()` | prompt + good prefix are computed exactly once |
| no compute-matched baseline | `restart` mode: same detector, but resample from scratch | isolates the speed contribution of checkpointing itself |
| 6 mutation pairs + 4 real-bug pairs + prove-or-refute | 3 mutation pairs, regex outcome proxy | methodology first; scale the dataset back up once the loop is trusted |

The three run modes share one code path (`prove(mode=...)`), so every comparison is
apples-to-apples: same sampler, same seeds, same detector.
"""

# --- Setup -------------------------------------------------------------
import os
from functools import partial

import pandas as pd

from evaluate import proxy_outcome, run_eval
from model import load_model_runtime
from prove import prove as run_proof
from rollback_rust import LEAN_MODELS, build_prompt
from draw import plot_timeline


PROJECT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".cache"
)
# DRY_RUN = os.environ.get("GEOMETRIC_CANARIES_DRY_RUN", "1") != "0"
DEVICE_REQUEST = os.environ.get("GEOMETRIC_CANARIES_DEVICE", "auto")

"""## Dataset — 3 Aeneas-style minimal pairs

Each item is a (fixed, buggy) pair in the Aeneas-faithful Lean subset (`Result` monad,
fallible machine-integer ops) with a spec that is provable for the fixed variant and
false for the buggy one. Three bug families kept for the prototype: loop progress
(`binary_search`), underflow panic (`sat_sub`), flipped comparison (`clamp`). The full
mutation + real-advisory dataset from the previous notebook drops back in unchanged once
the loop is trusted — `prove()` only needs `build_prompt(item, variant)`.
"""

MINIMAL_PAIRS = []
for name, m in LEAN_MODELS.items():
    MINIMAL_PAIRS.append({
        "id": name,
        "bug_type": m["bug_type"],
        "provenance": "mutation",
        "real_world_analogue": m["real_world_analogue"],
        "fixed": {"defn": m["fixed_defn"], "spec": m["spec"], "provable": True},
        "buggy": {"defn": m["buggy_defn"], "spec": m["spec"], "provable": False},
    })


print(f"{len(MINIMAL_PAIRS)} minimal pairs: "
      + ", ".join(p["id"] for p in MINIMAL_PAIRS))

"""## Segmentation and the bad-logic detector

A **segment** is a candidate reasoning step; boundaries are blank lines, enumerators,
discourse markers, and code fences. Detection is **causal and online**: the moment a
segment closes, it is scored against the running statistics of the segments before it —

- `z_ent` — segment mean next-token entropy vs. prior segments (the model is flailing)
- `z_drift` — cosine distance of the segment's hidden-state centroid from the running
  centroid of the accepted prefix (the geometric-canary signal)
- `smell` — lexical proof-smells (`sorry`, `obviously`, `it is easy to see`, …)

`score = 0.5·z_ent + 0.5·z_drift + 1.5·smell`, flag when `score > thresh`.
"""

"""## The `prove()` loop — checkpoint = KV-cache length

One manual decode loop drives all three conditions:

- **`plain`** — generate once, no intervention (baseline)
- **`rollback`** — on a flag, `cache.crop(checkpoint)`: the KV cache is truncated to the
  start of the flagged segment, an optional corrective hint is appended, and sampling
  continues. *The prompt and the good prefix are never recomputed* — a rollback costs
  only the hint tokens.
- **`restart`** — on a flag, throw everything away and re-prefill from the prompt
  (same detector, no checkpointing). This is the compute-matched control that isolates
  what checkpointing itself buys.

`n_forward` counts every token position pushed through the model (prefills + decode +
hints), which is the honest compute cost; abandoned branches are kept as counterfactual
data for the geometry analysis.
"""

"""## Visualization — signal timeline with rollback markers

Entropy (top) and chosen-token logprob (bottom) over the *live* trace. Segment
boundaries are vertical lines, flagged-then-rolled-back positions are red markers, and
hint injections show as gaps (hint tokens are forced, so they carry no sampling
entropy).
"""

"""## Evaluation — does checkpointing help, and is it cheaper?

3 items × 2 variants × 3 modes × seeds. Two questions, two tables:

1. **Detection/steering** — outcome by variant and mode. On *buggy* items the desired
   outcome is `claims_false` (the spec is false); on *fixed* items, `claims_proof`.
2. **Speed** — mean forward passes and wall-time per run, by mode. `rollback` vs.
   `restart` at equal intervention counts is the direct measure of what the checkpoint
   buys; the `saved` column is the re-prefill compute that `cache.crop()` avoided.

The outcome column is still the regex proxy — wire in Lean checking (last cell) before
believing any of the outcome numbers.
"""

def main():
    """Run one bounded smoke test; the full evaluation is opt-in."""
    import argparse

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--eval", action="store_true",
                        help="run the full comparison instead of one smoke test")
    parser.add_argument("--max-new-tokens", type=int, default=64,
                        help="generation limit per attempt (default: 64)")
    parser.add_argument("--plot", action="store_true",
                        help="show plots after generation")
    parser.add_argument("--dry-run", action="store_true",
                        help="use the small model for a smoke test")
    args = parser.parse_args()

    model, tokenizer, capture_layer = load_model_runtime(
        PROJECT_CACHE,
        dry_run=args.dry_run,
        device_request=DEVICE_REQUEST,
    )
    prove = partial(
        run_proof,
        model=model,
        tokenizer=tokenizer,
        capture_layer=capture_layer,
    )
    run_rollback_eval = partial(
        run_eval,
        MINIMAL_PAIRS,
        build_prompt,
        prove,
    )

    if not args.eval:
        item = MINIMAL_PAIRS[0]
        res = prove(
            build_prompt(item, "buggy"),
            mode="rollback",
            max_new_tokens=args.max_new_tokens,
            thresh=1.8,
            seed=0,
            verbose=True,
        )
        print(f"\nmode={res['mode']}  rollbacks={res['rollbacks']}  "
              f"segments={len(res['segments'])}")
        print(f"forward passes: {res['n_forward']}  "
              f"(prefills: {res['n_prefills']})  wall: {res['wall_s']:.1f}s")
        for event in res["events"]:
            print("  event:", event)
        print("\noutcome:", proxy_outcome(res["text"]))
        print("\n--- final text (tail) ---\n", res["text"][-800:])
        if args.plot:
            plot_timeline(res, title=f"{item['id']} / buggy / rollback")
        return

    # Lowering the threshold below zero guarantees interventions.
    df = run_rollback_eval(max_new_tokens=args.max_new_tokens, thresh=-1.0)
    print(df.to_string(index=False))
    print("\nOutcome by variant x mode:")
    print(pd.crosstab([df.variant, df["mode"]], df.outcome))

    print("\nCompute by mode:")
    comp = df.groupby("mode").agg(
        interventions=("interventions", "mean"),
        fw_passes=("n_forward", "mean"),
        prefills=("prefills", "mean"),
        wall_s=("wall_s", "mean"),
    ).round(1)
    comp["saved_vs_restart_fw"] = (
        comp.loc["restart", "fw_passes"] - comp["fw_passes"]
    ).round(0)
    print(comp)

    if args.plot:
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(6, 3.2))
        comp["fw_passes"].plot.bar(
            ax=ax, color=["gray", "tab:green", "tab:red"]
        )
        ax.set_ylabel("mean forward passes / run")
        ax.set_title("Compute cost by mode (lower = cheaper)")
        plt.tight_layout()
        plt.show()


if __name__ == "__main__":
    main()
