# -*- coding: utf-8 -*-
"""geometric_canaries_streaming_rollback_v0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBcF0p9xcDMIIoBWjI2_pDGF9zB4EKlH

# Geometric Canaries — streaming CoT checkpoint / rollback

**Question.** If we segment a proof attempt into reasoning steps, can we (a) catch faulty
logic at the step where it appears and (b) make proving *cheaper* by rolling back to the
last safe checkpoint instead of resampling from scratch?

**Model.** `deepseek-ai/DeepSeek-Prover-V2-7B`, 4-bit, single Colab GPU.
Set `DRY_RUN = True` to smoke-test the pipeline with a tiny model first.

**What changed vs. the previous notebook**

| before | now | why |
|---|---|---|
| generate 512 tokens → segment → detect → roll back | detect **online** at each segment boundary during generation | tokens after the first bad segment are never generated |
| rollback re-encodes the whole prefix every round | checkpoint = **KV-cache length**; rollback = `cache.crop()` | prompt + good prefix are computed exactly once |
| no compute-matched baseline | `restart` mode: same detector, but resample from scratch | isolates the speed contribution of checkpointing itself |
| 6 mutation pairs + 4 real-bug pairs + prove-or-refute | 3 mutation pairs, regex outcome proxy | methodology first; scale the dataset back up once the loop is trusted |

The three run modes share one code path (`prove(mode=...)`), so every comparison is
apples-to-apples: same sampler, same seeds, same detector.
"""

# --- Setup -------------------------------------------------------------
import argparse
import logging
import os
import pickle
import time
from datetime import datetime
from functools import partial
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import pandas as pd

from draw import plot_timeline
from evaluate import proxy_outcome, run_eval
from model import load_model_runtime
from prove import prove as run_proof
from rollback_rust import LEAN_MODELS, build_prompt

PROJECT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".cache"
)
# DRY_RUN = os.environ.get("GEOMETRIC_CANARIES_DRY_RUN", "1") != "0"
DEVICE_REQUEST = os.environ.get("GEOMETRIC_CANARIES_DEVICE", "auto")
FILEDIR = Path(__file__).parent / "log"
SINGLE_EXAMPLE_INDEX = 1
"""## Dataset — 3 Aeneas-style minimal pairs

Each item is a (fixed, buggy) pair in the Aeneas-faithful Lean subset (`Result` monad,
fallible machine-integer ops) with a spec that is provable for the fixed variant and
false for the buggy one. Three bug families kept for the prototype: loop progress
(`binary_search`), underflow panic (`sat_sub`), flipped comparison (`clamp`). The full
mutation + real-advisory dataset from the previous notebook drops back in unchanged once
the loop is trusted — `prove()` only needs `build_prompt(item, variant)`.
"""

MINIMAL_PAIRS = []
for name, m in LEAN_MODELS.items():
    MINIMAL_PAIRS.append({
        "id": name,
        "bug_type": m["bug_type"],
        "provenance": "mutation",
        "real_world_analogue": m["real_world_analogue"],
        "fixed": {"defn": m["fixed_defn"], "spec": m["spec"], "provable": True},
        "buggy": {"defn": m["buggy_defn"], "spec": m["spec"], "provable": False},
    })


print(f"{len(MINIMAL_PAIRS)} minimal pairs: "
      + ", ".join(p["id"] for p in MINIMAL_PAIRS))

"""## Segmentation and the bad-logic detector

A **segment** is a candidate reasoning step; boundaries are blank lines, enumerators,
discourse markers, and code fences. Detection is **causal and online**: the moment a
segment closes, it is scored against the running statistics of the segments before it —

- `z_ent` — segment mean next-token entropy vs. prior segments (the model is flailing)
- `z_drift` — cosine distance of the segment's hidden-state centroid from the running
  centroid of the accepted prefix (the geometric-canary signal)
- `smell` — lexical proof-smells (`sorry`, `obviously`, `it is easy to see`, …)

`score = 0.5·z_ent + 0.5·z_drift + 1.5·smell`, flag when `score > thresh`.
"""

"""## The `prove()` loop — checkpoint = KV-cache length

One manual decode loop drives all three conditions:

- **`plain`** — generate once, no intervention (baseline)
- **`rollback`** — on a flag, `cache.crop(checkpoint)`: the KV cache is truncated to the
  start of the flagged segment, an optional corrective hint is appended, and sampling
  continues. *The prompt and the good prefix are never recomputed* — a rollback costs
  only the hint tokens.
- **`restart`** — on a flag, throw everything away and re-prefill from the prompt
  (same detector, no checkpointing). This is the compute-matched control that isolates
  what checkpointing itself buys.

`n_forward` counts every token position pushed through the model (prefills + decode +
hints), which is the honest compute cost; abandoned branches are kept as counterfactual
data for the geometry analysis.
"""

"""## Visualization — signal timeline with rollback markers

Entropy (top) and chosen-token logprob (bottom) over the *live* trace. Segment
boundaries are vertical lines, flagged-then-rolled-back positions are red markers, and
hint injections show as gaps (hint tokens are forced/injected, so they carry no sampling
entropy).
"""

"""## Evaluation — does checkpointing help, and is it cheaper?

3 items × 2 variants × 3 modes × seeds. Two questions, two tables:

1. **Detection/steering** — outcome by variant and mode. On *buggy* items the desired
   outcome is `claims_false` (the spec is false); on *fixed* items, `claims_proof`.
2. **Speed** — mean forward passes and wall-time per run, by mode. `rollback` vs.
   `restart` at equal intervention counts is the direct measure of what the checkpoint
   buys; the `saved` column is the re-prefill compute that `cache.crop()` avoided.

The outcome column is still the regex proxy — wire in Lean checking (last cell) before
believing any of the outcome numbers.
"""


def stop_reason_label(stop_reason: str) -> str:
    """Human-readable explanation of why generation ended."""
    labels = {
        "eos": "eos (model emitted end-of-sequence)",
        "max_new_tokens": "max_new_tokens (hit generation budget)",
    }
    return labels.get(stop_reason, str(stop_reason))


def show_single_result(
    res: dict[str, Any],
    item: dict[str, Any],
) -> None:
    """Print and plot one generated proof result."""
    print(f"\nmode={res['mode']}  rollbacks={res['rollbacks']}  "
          f"segments={len(res['segments'])}")
    print(f"forward passes: {res['n_forward']}  "
          f"(prefills: {res['n_prefills']})  wall: {res['wall_s']:.1f}s")
    print(f"stopped: {stop_reason_label(res.get('stop_reason', 'unknown'))}")
    for event in res["events"]:
        print("  event:", event)
    print("\noutcome:", proxy_outcome(res["text"]))
    if res.get("prompt") is not None:
        print("\n--- prompt ---\n", res["prompt"])
    print("\n--- final text ---\n", res["text"])
    print("-" * 50)
    plot_timeline(res, title=f"{item['id']} / buggy / rollback")


def show_run_generations(df: pd.DataFrame) -> None:
    """Print the prompt, events, and generated text for every evaluation run."""
    if "text" not in df.columns:
        print("\n(no text column in this cache; re-run eval to record generations)")
        return

    print("\n" + "=" * 50)
    print("Per-run generations")
    print("=" * 50)
    for _, row in df.iterrows():
        print(
            f"\n=== {row['id']} / {row['variant']} / {row['mode']} "
            f"seed={row['seed']} ==="
        )
        print(
            f"outcome={row['outcome']}  interventions={row['interventions']}  "
            f"gen_tokens={row['gen_tokens']}  wall_s={row['wall_s']:.1f}"
        )
        stop_reason = (
            row["stop_reason"] if "stop_reason" in df.columns else "unknown"
        )
        print(f"stopped: {stop_reason_label(stop_reason)}")
        events = row["events"] if "events" in df.columns else None
        if isinstance(events, (list, tuple)) and events:
            for event in events:
                print("  event:", event)
        if "prompt" in df.columns and isinstance(row["prompt"], str):
            print("\n--- prompt ---\n", row["prompt"])
        print("\n--- final text ---\n", row["text"])
        print("-" * 50)


def show_eval_result(df: pd.DataFrame) -> None:
    """Print summary tables, then each run's events and final text."""
    # Keep the comparison table readable when text/prompt are present.
    summary_cols = [
        c for c in df.columns
        if c not in ("text", "prompt", "events")
    ]
    print(df[summary_cols].to_string(index=False))
    print("\nOutcome by variant x mode:")
    outcome_table = pd.crosstab(
        [df.variant, df["mode"]], df.outcome
    ).reindex(
        columns=["claims_proof", "claims_false", "no_conclusion"],
        fill_value=0,
    )
    print(outcome_table)

    print("\nCompute by mode:")
    comp = df.groupby("mode").agg(
        interventions=("interventions", "mean"),
        fw_passes=("n_forward", "mean"),
        prefills=("prefills", "mean"),
        wall_s=("wall_s", "mean"),
    ).round(1)
    comp["saved_vs_restart_fw"] = (
        comp.loc["restart", "fw_passes"] - comp["fw_passes"]
    ).round(0)
    print(comp)

    show_run_generations(df)

    fig, ax = plt.subplots(figsize=(6, 3.2))
    comp["fw_passes"].plot.bar(
        ax=ax, color=["gray", "tab:green", "tab:red"]
    )
    ax.set_ylabel("mean forward passes / run")
    ax.set_title("Compute cost by mode (lower = cheaper)")
    plt.tight_layout()
    plt.show()


def result_path(filedir: str | Path, timestamp: str) -> Path:
    """Return ``filedir/result_<timestamp>.pkl``."""
    return Path(filedir) / f"result_{timestamp}.pkl"


def load_result(
    filedir: str | Path,
    timestamp: str,
) -> dict[str, Any]:
    """Load a cached results pickle for the given timestamp.

    The file may contain both the single-example result and the full-evaluation
    DataFrame. The earlier format, which stored only one result, is converted
    into the current in-memory collection when loaded.
    """
    path = result_path(filedir, timestamp)
    if not path.exists():
        raise FileNotFoundError(f"No cache found: {path}")
    print(f"Loading cache: {path=}")
    with path.open("rb") as file:
        saved = pickle.load(file)
    if "result" in saved:
        saved = {"single_example": saved}
    return saved


def save_result(
    filedir: str | Path,
    results: dict[str, Any],
    name: str,
    result: Any,
) -> str:
    """Add one result, write ``result_<timestamp>.pkl``, return the timestamp."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = result_path(filedir, timestamp)
    results[name] = {
        "saved_at": timestamp,
        "result": result,
    }
    Path(filedir).mkdir(parents=True, exist_ok=True)
    with path.open("wb") as file:
        pickle.dump(results, file)
    print(f"Saved result: {name=}, {path=}")
    print(f"You can reload later with: --load-saved {timestamp}")
    return timestamp


def main() -> None:
    """Run the full evaluation, or one example when requested."""
    start_time = time.perf_counter()
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--single-example",
        action="store_true",
        help="run one example instead of the full comparison",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=2048,
        help="generation limit per attempt (default: 2048)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="use the small model for a quick run",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="show detailed generation and rollback state",
    )
    parser.add_argument(
        "--load-saved",
        metavar="TIMESTAMP",
        help=(
            "load log/result_<TIMESTAMP>.pkl instead of running "
            "(e.g. 20260803_221329)"
        ),
    )
    args = parser.parse_args()
    logging.basicConfig(
        level=logging.WARNING,
        format="%(levelname)s: %(message)s",
    )
    if args.debug:
        logging.getLogger("prove").setLevel(logging.DEBUG)
    print(f"Max new tokens: {args.max_new_tokens}")
    result_name = "single_example" if args.single_example else "full_eval"
    
    if args.single_example:
        print(f'{SINGLE_EXAMPLE_INDEX=}')

    if args.load_saved:
        results = load_result(FILEDIR, args.load_saved)
        saved = results[result_name]
        result = saved["result"]
        print(result.keys())
        exit()
        saved_at = saved["saved_at"]
        print(f"Using cached result: {result_name=}, {saved_at=}")
        print(f'{result=}')
        if args.single_example:
            show_single_result(result, MINIMAL_PAIRS[SINGLE_EXAMPLE_INDEX])
        else:
            show_eval_result(result)
        total_time = time.perf_counter() - start_time
        print(f"{total_time=:.1f}")
        return

    results = {}
    model, tokenizer, capture_layer = load_model_runtime(
        PROJECT_CACHE,
        dry_run=args.dry_run,
        device_request=DEVICE_REQUEST,
    )

    prove = partial(
        run_proof,
        model=model,
        tokenizer=tokenizer,
        capture_layer=capture_layer,
    )
    run_rollback_eval = partial(
        run_eval,
        MINIMAL_PAIRS,
        build_prompt,
        prove,
    )
    if args.single_example:
        item = MINIMAL_PAIRS[SINGLE_EXAMPLE_INDEX]
        res = prove(
            build_prompt(item, "buggy"),
            mode="rollback",
            max_new_tokens=args.max_new_tokens,
            thresh=1.8,
            seed=0,
        )
        save_result(FILEDIR, results, result_name, res)
        show_single_result(res, item)
        total_time = time.perf_counter() - start_time
        print(f"{total_time=:.1f}")
        return

    # Lowering the threshold below zero guarantees interventions.
    df = run_rollback_eval(max_new_tokens=args.max_new_tokens, thresh=-1.0)
    save_result(FILEDIR, results, result_name, df)
    show_eval_result(df)
    total_time = time.perf_counter() - start_time
    print(f"{total_time=:.1f}")


if __name__ == "__main__":
    main()
